climatetree/stories-microservice

- .gitignore
- .idea/backend-mongo.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- .travis.yml
- app.js
- controllers/solutions.controller.js
- models/solutions.model.js
- package-lock.json
- package.json
- routes/solutions.route.js
- tests/sample.test.js
Created basic node.js application
created basic controller model and router
Added travis configuration.
> Basic setup

- app.js
- controllers/getStoryByID_controller.js
- models/story.model.js
- routes/story.route.js
> Add 3 files for achieving first API.

- .travis.yml
Sets up mongodb for travis environment
Creates a database `mydb_test`
With username and password as `user` and `password`
> Setup mongodb travis

- .dockerignore
- Dockerfile
- db/db.js
Containerizes the nodejs project for deployment
Steps to run locally 
``` docker
docker build -t climatetree/node-web-app .
docker run -p 49160:1234 -i -e MONGO_URL=docker.for.mac.host.internal climatetree/node-web-app
```
TODO
- Building and publishing to docker hub
> Containerize nodejs

- pull_request_template.md
Adds pull request template to to project root autofill PRs.
> DevOps - add pull request template

- dao/story.dao.server.js
- db/db.js
- routes/story.route.server.js
- Bug fix 
Version problem fixed
-
> Version problem fixed, add remote configuration.

- .travis.yml
- Dockerfile
- db/db.js
- docker_push.sh
Added deploy scripts.  
Set up deploy on master.
Use environment variables for connections.
-
> Docker hub push

- .travis.yml
> Call docker_push script correctly

- .travis.yml
New feature
Links travis ci for this repo with backend slack channel
https://trello.com/c/hCstqZZl/78-connect-travis-bot-to-slack-to-send-build-failure-messages
[True ] Changes do not introduce new warnings or errors
If the build fails slack channel #public-backend will be notified about it
> link travis and slack

- dao/story.dao.server.js
- schemas/story.schema.server.js
- tests/story.test.js
- New feature
- Removed story_id
- Will be using the default _id
- Modified tests
> Removed story_id. Will be using the default _id

- routes/story.route.server.js
Changed delete endpoint to '/stories/delete/:storyId'
Changed update endpoint to '/stories/udpate/:storyId
> Changed endpoints of delete and update APIs

- app.js
- New feature
- Enabled CORS for localhost and climatetree.azurewebsites.net
- Check if frontend team can hit these API and not get CORS errors.
> Enabled CORS for localhost and climatetree.azurewebsites.net

- routes/story.route.server.js
- tests/story.test.js
-  Bug fix
- Add response status codes for every endpoint 
https://trello.com/c/wPM5qMq2/54-use-appropriate-response-status-codes-for-every-response
-
> Add appropriate response status codes and handle errors

- docker_push.sh
> Tag images correctly when pushing to docker hub

- dao/story.dao.server.js
- db/db.js
- routes/story.route.server.js
case-insensitive keyword search on title added,
> Keyword search on title added

- dao/story.dao.server.js
- db/db.js
- models/story.model.server.js
- package-lock.json
- package.json
- routes/story.route.server.js
- schemas/story.schema.server.js
- tests/story.test.js
story_id as partition key, story_id is generated by service, updates tests, fixed warnings
> (latter one)story_id as partition key, story_id is generated by service, updates tests, fixed warnings

- dao/story.dao.server.js
- db/db.js
- docker_push.sh
- models/story.model.server.js
- package-lock.json
- package.json
- routes/story.route.server.js
- schemas/story.schema.server.js
- tests/story.test.js
1. service generates ID
2. add one fields "story_id" into schema
3. updates some tests
4. connected to "test" collection, which is the large collection with 50,000 cities.
> Merge develop branch to master

- routes/story.route.server.js
Fixed a bug in findStoryByPlaceID.
Fixed some warnings.
> Fixed a bug in findStoryByPlaceID.

- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
Added API to fetch n most recent stories
Added tests for the API
Endpoint: /stories/topStories/:numberOfStories
> API to find top n stories added with tests

- .travis.yml
https://trello.com/c/nhSan75D/81-remove-mongodb-setup-from-travis-configuration-for-stories-microservice-repo-would-speed-up-travis
- Changes do not introduce new warnings or errors
- [All new and existing tests pass
> removed mongodb setup from travis

- README.md
- dao/story.dao.server.js
- routes/story.route.server.js
- schemas/story.schema.server.js
- tests/comment.test.js
- tests/story.test.js
- New feature - Like and unlike a story by a user
API endpoints - 
Like a story: /stories/:storyID/like/:userID
Unlike a story: /stories/:storyID/unlike/:userID
https://trello.com/c/yglb43Uw/64-likes-on-stories
https://trello.com/c/0SeUwIXg/72-unlike-a-story
> Like and unlike a story

- models/comments.model.server.js
- models/story.model.server.js
> Update db connection

- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
Added pagination to findStoriesByTitle API
> Added pagination to findStoriesByTitle API

- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
Paginated the getStoriesByPlaceID API
> Paginated the getStoriesByPlaceID API

- .eslintrc.json
- app.js
- dao/comment.dao.server.js
- dao/story.dao.server.js
- db/db.js
- package-lock.json
- package.json
- routes/story.route.server.js
- schemas/story.schema.server.js
- tests/comment.test.js
- tests/story.test.js
> Add linter and pre commit hook to check eslint

- tests/comment.test.js
- tests/story.test.js
1. Modified the port used in comment.test.js. Now two test files won‘’t use the same port.
2. Updated tests. Now it won't report errs.
> Updates on tests.

- db/db.js
- Bug fix 
- Changed the connection string to local host for running tests locally. Prior connected to azure database.
https://trello.com/c/Q4dHSSbg/102-changed-connection-string-of-db-for-local-tests
- npm test should run locally without any internet connection
> Changed connection string to connect to localhost for local tests

- constants/role.js
- routes/story.route.server.js
- tests/comment.test.js
- Add roles
- Modify delete comment to include role
- Modify tests to include role
- Added a file to save role value sent as defined by User-service team
- Modified delete comments to check for roles
- Note to reviewers: Manually tested on postman along with unit test
https://trello.com/c/S2tTixgA/86-allow-moderators-and-admin-to-delete-comments-made-by-other-users-6
- run npm test
> Delete by role

- package-lock.json
- package.json
- routes/story.route.server.js
- tests/story.test.js
- New feature
- Implements a new endpoint
- Note to reviewers: 
This endpoint is for routing "grabity" requests through our domain name to circumvent CORS
https://trello.com/c/5WwPl5JL/76-create-an-endpoint-getpreview-which-returns-meta-data-for-a-hyperlink-if-given-a-hyperlink-2
- run npm test
> Get preview

- constants/role.js
- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
- New feature
- Allow Admins and Moderators to add rating to a story
- Update Story method in DAO now returns the updated document
https://trello.com/c/zvlKSCg7/100-allow-moderators-and-admin-to-add-rating-to-a-story
-
> Moderator rating

- routes/story.route.server.js
- tests/story.test.js
Added checks and tests
- Bug fix 
- Added check for negative parameters passed from frontend for pagination
https://trello.com/c/SLHNts1R/103-add-checks-for-negative-params-for-pagination
- run npm test
> Add check for negative and 0 page number and limit for pagination

- dao/story.dao.server.js
- routes/story.route.server.js
- schemas/story.schema.server.js
- tests/story.test.js
Updated story schema given Greg's requirements
+ description:String added
+ strategy:String[] added
+ sector:String -> String[]
One new API added in story.dao:
+ findStoryByDescription (desc,limit,page) -> story
One new endpoint added in route:
+ findStoryByDescription (desc,limit,page) -> story
get: /stories/description/:description
Tests added for new APIs in dao and routes
> new APIs "findStoryByDescription" in DAO and routes added and Schema changed

- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
- New feature
- API for finding unrated stories (default 0 rating) for moderators (paginated).
https://trello.com/c/cr7bSXb6/104-api-to-return-all-the-stories-which-havent-been-reviewed-ie-rating-is-null-for-the-moderators
-
> API for finding unrated stories (Stories with rating 0)

- routes/story.route.server.js
- tests/story.test.js
> corrected response codes

- dao/comment.dao.server.js
- routes/story.route.server.js
- schemas/comment.schema.server.js
> added username in comments schema, to return username in comments

- routes/story.route.server.js
- Modify existing feature
- return comment instead of story
- Tested on postman
https://trello.com/c/GcAigA7T/105-modify-addcomment-to-return-comment-instead-of-story
- run npm test
> Modify add comment endpoint to return added comment instead of updated story

- dao/story.dao.server.js
- routes/story.route.server.js
- schemas/story.schema.server.js
- tests/story.test.js
Add tests to test flag and unflag
- New feature
- Schema changed to add flagging
- Flag and unflag logic is same as like and unlike
https://trello.com/c/PFJ9JVIB/107-create-api-to-flag-and-unflag-a-story
- Run npm test
> Add feature to flag and unflag a story

- tests/story.test.js
Fixed minor typos in test names
> Fixed minor typos in tests

- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
Added findStoriesBySolution API.
Endpoint: /stories/solution/:solution
> Adding findStoriesBySolution API

- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
Added findStoriesByStrategy and findStoriesBySector APIs.
Endpoints: (1) /stories/strategy/:strategy (2) /stories/sector/:sector
> Added findStoriesBySector and findStoriesByStrategy APIs

- schemas/story.schema.server.js
- tests/comment.test.js
- tests/story.test.js
Add tests for new schema requirements
Change earlier tests to account for new schema
- Schema change and testing
- Fields are made required
- Default values are added for fields
- Schema is changed
https://trello.com/c/UGnF7je1/113-schema-change-and-making-fields-required-and-have-default-values
- run npm test
> Change schema and make fields required and have default values

- routes/story.route.server.js
- tests/story.test.js
Endpoints:
/stories/all/strategy
/stories/all/solution
/stories/all/sector
These are hardcoded APIs that will be updated once the collection for storing these values is finalized.
> Added hardcoded get all stories, solutions and strategy API

- routes/story.route.server.js
- tests/story.test.js
Endpoints:
/stories/all/strategy/:strategy
/stories/all/solution/:solution
/stories/all/sector/:sector
These are hardcoded APIs that will be updated once the collection for storing these values is finalized.
> Added hardcoded findSectorByName, findSolutionByName and findStrategyByName APIs

- dao/taxonomy.dao.server.js
- models/taxonomy.model.server.js
- routes/story.route.server.js
- schemas/taxonomy.schema.server.js
- tests/taxonomy.test.js
- Taxonomy schema added
- New API in Dao added
- New endpoints for obtaining solution&&strategy&&sector added
- Tests for above APIs and endpoints added
- fixed some warning by adding semicolons
- Taxonomy Schema:{
strategy:String,
sector:String,
solution:String}
- endpoints:
app.get('/stories/taxonomy',findAllTaxonomy);
app.get('/stories/taxonomy/solution/:solution',findTaxonomyBySolution);
app.get('/stories/taxonomy/strategy/:strategy',findTaxonomyByStrategy);
app.get('/stories/taxonomy/sector/:sector',findTaxonomyBySector);
- APIs in Dao:
+ findAllTaxonomy
+ findTaxonomyBySolution
+ findTaxonomyBySector
+ findTaxonomyByStrategy
-
> Taxonomy added. Now can get solution&&strategy&&sector from database

- routes/story.route.server.js
- tests/story.test.js
As solutions, strategy and sector have moved to a new collection, removing the code for the previously hardcoded APIs.
> Removed duplicate/unused code

- routes/story.route.server.js
- tests/comment.test.js
- tests/story.test.js
- tests/taxonomy.test.js
- API versioning
- Version all the APIs from Stories microservice to version 1
https://trello.com/c/nzRX5SpV/115-api-versioning
-
> API versioning for Stories

- routes/story.route.server.js
- tests/story.test.js
Add test to test for error code 200 on deletion
- Bug fix 
- Send error code 200 instead of 500 on deletion
- Add test to check for error code
https://trello.com/c/e1ZmzcOH/116-remove-bug-for-delete-story-and-add-test-for-that
- npm test
> Remove bug of sending error code 500 in delete story

- dao/media.dao.server.js
- models/media.model.server.js
- routes/story.route.server.js
- schemas/media.schema.server.js
- schemas/story.schema.server.js
- tests/story.test.js
- New feature
- Add a new collection that returns a list of acceptable media types
https://trello.com/c/7tn69KMo/117-add-media-types-to-database
-
> Add collection 'media_type'

- dao/story.dao.server.js
- routes/story.route.server.js
- tests/story.test.js
Add test to check endpoint
- New feature
- Adds new enpoint to return stories given a user_id
https://trello.com/c/y2plFbdz/124-add-endpoint-to-search-for-story-given-userid
- run npm test
> Add endpoint for finding story given user_id

- dao/taxonomy.dao.server.js
- routes/story.route.server.js
- tests/taxonomy.test.js
Two methods added in taxonomy.dao.server.js
+ findAllSolution
+ findAllSector
Two new endpoints added in story.route.server.js
+ GET findAllSolution /v1/stories/taxonomy/all/solution
+ GET findAllSector /v1/stories/taxonomy/all/sector
Tests added for two APIs in dao and two endpoints in route, 4 in total.
> Add two Taxonomy APIs

- routes/story.route.server.js
- Bug fix 
- While solving merge conflict a function was declared twice hence the build failed.
this removes the second declaration of the function
-  npm test
> Remove second declaration of getSortedByFlagged

- package-lock.json
- package.json
> Update minimist package in dev dependancy

- db/db.js
- Everything works on deployment and locally by setting all env variables
> Configure env variable for mongodb connection to hosted VM

- dao/comment.dao.server.js
- dao/es.story.dao.server.js
- db/db.js
- schemas/story.schema.server.js
- tests/comment.test.js
- tests/story.test.js
- tests/taxonomy.test.js
Disable local connect to disable err in CI tests
Fixed timeout problems in story tests
> Fix tests errs

- dao/es.story.dao.server.js
findStoryBySolution
findStoryBySector
findStoryByStrategy
advanceSearch
> Fixed errs that cannot search with space and uppercase in following APIs:

- dao/es.story.dao.server.js
Fixed a bug that a err happens should end function rather than continuing executing.
Added:
add "return" for each end of "failCallback"
> Fixed a bug that a err happens should end function rather than continuing executing.
